version: '3.9'

services:
  backend:
    build: ./back
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    depends_on:
      - mysql

  frontend:
    build: ./front
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
    command: sh -c "npm install && npm run dev"
    working_dir: /app

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sandboxdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
